site_name: ehviewer·(白色版)官方网站-入口
site_author: ehviewer·(白色版)官方网站-入口
site_description: ehviewer白色版是专注二次元安全浏览的图片应用，提供纯净的ACG内容下载入口观赏体验，适合所有年龄用户使用。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
